name: Telegram Updates
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: send push update
        if: ${{ github.event_name == 'push'}}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: ${{github.repository}} - ${{github.actor}} just pushed to branch ${{ steps.vars.outputs.branch }}.

      - name: send PR open update
        if: ${{ github.event.pull_request.opened}}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: ${{github.repository}} - ${{github.actor}} opened a new pull request from ${{github.head_ref}} to ${{github.base_ref}}.

      - name: send PR merged update
        if: ${{ github.event.pull_request.merged}}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: ${{github.repository}} - ${{github.actor}} merged pull request ${{github.event.number}} from ${{github.head_ref}} to ${{github.base_ref}}.
