name: Telegram Updates
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
  push_update:
    name: send push update
    if: ${{ github.event_name == 'push'}}
    steps:
      - uses: appleboy/telegram-action@master
      - name: send push update
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: ${{github.repository}} - ${{github.actor}} just pushed to branch ${{ steps.vars.outputs.branch }}.
  pr_update:
    name: send PR update
    if: ${{ github.event_name == 'pull_request'}}
    steps:
      - uses: appleboy/telegram-action@master
      - name: send PR update
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: ${{github.repository}} - ${{github.actor}} opened a new pull request from ${{github.head_ref}} to ${{github.base_ref}}.
